# Pipeline settings
enable_training: true
enable_evaluation: true

# Model settings
model:
  # available choices in pipeline.schemas.constants.ModelBackbone
  backbone: resnet18
  num_classes: 2
  weights: DEFAULT
  checkpoint_path: null

# Dataloader settings
dataloader:
  trainset_dir: ./tests/test_dataset/
  valset_dir: ./tests/test_dataset/
  testset_dir: null
  batch_size: 4
  num_workers: 2

# Preprocessing settings
preprocessing:
  # To compute mean and std, one can use the following command:
  # poetry run python3 -m pipeline compute-mean-and-std -d <path to dataset>
  # Or, one can use the Makefile command
  # DATA_DIR=<path to dataset> make compute-mean-and-std
  mean: [0.47488933801651, 0.4632834792137146, 0.4371258318424225]
  std: [0.21972933411598206, 0.22210058569908142, 0.22161932289600372]

  resize_config:
    width: 48
    height: 48
    # available choices in pipeline.schemas.constants.InterpolationType
    interpolation: inter_cubic
    # available choices in pipeline.schemas.constants.PaddingType
    padding: bottom_right
    maintain_aspect_ratio: true

  spatial_config:
    # Probability in [0., 1.]
    hflip_prob: 0.5
    vflip_prob: 0.5
    max_rotate_in_degree: 10
    allow_center_crop: false
    allow_random_crop: false

  color_config:
    allow_gray_scale: false
    allow_random_color: false

# Training settings
training:
  name: experiment
  device: cuda
  precision: 64
  random_seed: 42
  num_epochs: 20
  max_num_hrs: null
  validate_every_n_epoch: 1
  save_every_n_epoch: 1
  patience_in_epoch: 10
  # available choice: loss, accuracy
  criterion: loss
  export_last_as_onnx: true
  export_best_as_onnx: true

  scheduler:
    # available choices in pipeline.schemas.constants.SchedulerType
    name: step
    lr_min: 0
    # Only for step
    step_size: 30
    # Only for step
    gamma: 0.1

  optimizer:
    # available choices in pipeline.schemas.constants.OptimizerType
    name: adam
    lr: 1e-7
    weight_decay: 0
    # Only used for sgd / rmsprop
    momentum: 0.9
    # Only used for rmsprop
    alpha: 0.99
    # Only used for adam / adamw
    betas: [0.9, 0.999]

# Evaluation settings
evaluation:
  name: experiment
  device: cuda
  precision: 64
  random_seed: 42
  evalset_dir: ./tests/test_dataset/
  models:
    - backbone: resnet18
      num_classes: 2
      weights: DEFAULT
      checkpoint_path: null
