experiment_label: "experiment"
random_seed: 42
device: cuda
enable_evaluation: true

# Settings about model
model:
  # For available choices, see "ModelBackbone" in src/schemas/constants.py
  backbone: resnet18
  num_classes: 2
  weights: DEFAULT
  unfreeze_all_params: false
  weights_path: null

# Settings about dataloader
dataloader:
  # For poetry enviorment, input relative path/absolute path to the trainset
  # For docker enviorment, input ${DATA_DIR}/< path to the trainset within that folder>
  trainset_dir: ../dataset/train/
  valset_dir: ../dataset/val/
  batch_size: 8
  num_workers: 4

preprocessing:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

  resize_config:
    width: 48
    height: 48
    # For available choices, see "InterpolationType" in src/schemas/constants.py
    interpolation: inter_cubic
    # For available choices, see "PaddingType" in src/schemas/constants.py
    padding: bottom_right
    maintain_aspect_ratio: true

  spatial_config:
    # Probability in [0., 1.]
    hflip_prob: 0.5
    vflip_prob: 0.5
    max_rotate_in_degree: 10 # in degrees
    allow_center_crop: false
    allow_random_crop: false

  color_config:
    allow_gray_scale: false
    allow_random_color: false

training:
  num_epochs: 20
  # available choice: loss, accuracy
  best_criteria: loss
  save_last_weight: true
  save_best_weight: true
  export_last_weight: true
  export_last_as_onnx: true
  export_best_weight: true
  export_best_as_onnx: true

  scheduler:
    # For available choices, see "SchedulerType" in src/schemas/constants.py
    name: step
    lr_min: 0
    step_size: 30 # Only for step
    gamma: 0.1 # Only for step

  optimizer:
    # For available choices, see "OptimizerType" in src/schemas/constants.py
    name: adam
    lr: 0.001
    weight_decay: 0
    # Only used for sgd / rmsprop
    momentum: 0.9
    # Only used for rmsprop
    alpha: 0.99
    # Only used for adam / adamw
    betas: [0.9, 0.999]

evaluation:
  evalset_dir: ../dataset/val
  mapping_path: class_mapping.yml
  models:
    - name: default
      weights_path: ./best_model.pt
      backbone: resnet18
